### ISSUE TITLE
Connect to MediaFlux desktop client

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data#3]
View secrets for connectivity in LastPass. (search for tigerdata)

We should see files and upload a file.

## Acceptance criteria

- [x] Bess 
- [x] Carolyn
- [x] Hector
- [x] James
- [x] Kate
- [x] Chuck

**Comment by carolyncole** [comment]
This seems to require VPN.  An I got an unsafe warning on my browser

**Comment by mccalluc** [comment]
For context, this is the error. I'd prefer to hold off on this until the error can be resolved. I'll ask on slack if there's someone we can reach out to...

> Warning: Potential Security Risk Ahead
> 
> Firefox detected an issue and did not continue to arca.rc.princeton.edu. The website is either misconfigured or your computer clock is set to the wrong time.
> 
> It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
> 
> What can you do about it?
> 
> The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Comment by hectorcorrea** [comment]
I was able to login without VPN. I used `http` instead of `https` to bypass the warning for now.

I was able to "create an asset", it's under collection "samples3/net/hector-test-three" but it has no content. I have no idea how to add content to it.

**Comment by carolyncole** [comment]
I can not connect without the VPN.  With the VPN I can login, and if I shut down the DIT (I had to shut it down, log out, disconnect from VPN, reconnect to VPN, re login to shut down DTI) I was able to drag and drop a file into the acme folder.

**Comment by jrgriffiniii** [comment]
As was the case with @carolyncole, I found it necessary to be authenticated over the VPN in order to access the web browser client. However, once successfully authenticated, I was indeed able to view files, download files, and upload my own test file.
