### ISSUE TITLE
Find online Mediaflux documentation

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data#33]
The _Mediaflux Developer Guide_ on p. 4 says:
> The on-line help can be found by going to `http://<mf-host>/mflux/help` and logging in. Once the concepts
> in this guide are understood, this online documentation is typically the most used source of documentation.

I have tried https://arca.rc.princeton.edu/mflux/help and http://arca.rc.princeton.edu/mflux/help and in both cases the response is 
> **404 - Not Found**
> 
> We're sorry, the URL you have supplied is invalid.
> 
> Please contact the system administrator if you believe it is correct.

- [ ] Find a URL that works for the on-line documentation
- [ ] Document it in our own "Missing Manual"

OR

- [x] If we learn that the online help would just be the same as the "Mediaflux Services Documentation" we already have, then it's not worth bothering about this particular 404.

**Comment by kevinabbey** [comment]
https://cses.princeton.edu/tickets/Ticket/Display.html?id=42087

**Comment by mccalluc** [comment]
Thanks! Checked the last box. Closing.
