### ISSUE TITLE
Basic operations of MediaFlux API via Python client

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data#4]
Use https://gitlab.unimelb.edu.au/resplat-mediaflux/python-mfclient to do initial connect/file and metadata lifecycle operations against MediaFlux sandbox.

Download the code 
1. https://gitlab.unimelb.edu.au/resplat-mediaflux/python-mfclient (You do not need to clone the repo. You only need https://gitlab.unimelb.edu.au/resplat-mediaflux/python-mfclient/-/blob/master/src/mfclient.py)
1. ~~https://gitlab.unimelb.edu.au/resplat-mediaflux/mflux-python-utilities~~ (These seem to b python2)
1. https://gitlab.unimelb.edu.au/resplat-mediaflux/python-mfclient/-/tree/master/examples (start with [quick start](https://gitlab.unimelb.edu.au/resplat-mediaflux/python-mfclient/-/blob/master/examples/quick_start.py)) to test your connectivity
    `python3 quick_start.py` to run the file
1. choose other examples and run them

Folks should keep track of what they run and commit it as PRs to tiger data. **NO Secrets  (password, user, url) includes please**

## Acceptance
- [ ] [Connect](https://gitlab.unimelb.edu.au/resplat-mediaflux/mflux-python-utilities/-/blob/master/mf_connect.py) to MediaFlux via Python client
- [ ] Add a file
- [ ] Download a file
- [ ] Modify a file
- [ ] Get metadata
- [ ] Update metadata

**Comment by carolyncole** [comment]
**Note:** The utilities are python 2 and likely will not work with Python 3

**Comment by jrgriffiniii** [comment]
This has been deprecated following newer issues created on 11/07/22.
